{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "49f889e8",
   "metadata": {
    "vscode": {
     "languageId": "javascript"
    }
   },
   "outputs": [],
   "source": [
    "// ==================== 2FA Routes ====================\n",
    "\n",
    "// 1. Verify 2FA during Login\n",
    "app.post(\"/api/auth/2fa/verify-login\", async (req, res) => {\n",
    "  try {\n",
    "    const { tempToken, code } = req.body;\n",
    "    \n",
    "    if (!tempToken || !code) {\n",
    "      return res.status(400).json({ message: \"Token and code are required\" });\n",
    "    }\n",
    "\n",
    "    // Verify temp token\n",
    "    let decoded;\n",
    "    try {\n",
    "      decoded = jwt.verify(tempToken, SECRET_KEY);\n",
    "    } catch (err) {\n",
    "      return res.status(401).json({ message: \"Invalid or expired session\" });\n",
    "    }\n",
    "\n",
    "    if (decoded.type !== \"2fa_pending\") {\n",
    "      return res.status(401).json({ message: \"Invalid token type\" });\n",
    "    }\n",
    "\n",
    "    const user = await User.findById(decoded.userId);\n",
    "    if (!user) {\n",
    "      return res.status(404).json({ message: \"User not found\" });\n",
    "    }\n",
    "\n",
    "    // Verify TOTP code\n",
    "    const isValid = authenticator.check(code, user.twoFactorSecret);\n",
    "    if (!isValid) {\n",
    "      return res.status(400).json({ message: \"Invalid 2FA code\" });\n",
    "    }\n",
    "\n",
    "    // Generate real auth token\n",
    "    const token = jwt.sign(\n",
    "      { \n",
    "        userId: user._id, \n",
    "        username: user.username,\n",
    "        email: user.email \n",
    "      },\n",
    "      SECRET_KEY,\n",
    "      { expiresIn: \"7d\" }\n",
    "    );\n",
    "\n",
    "    res.cookie('token', token, {\n",
    "      httpOnly: true,\n",
    "      secure: process.env.NODE_ENV === 'production',\n",
    "      sameSite: process.env.NODE_ENV === 'production' ? 'none' : 'lax',\n",
    "      maxAge: 7 * 24 * 60 * 60 * 1000,\n",
    "      path: '/'\n",
    "    });\n",
    "\n",
    "    // Calculate subscription status (reused logic)\n",
    "    let hasActiveSubscription = false;\n",
    "    if (user.isSubscribed && user.subscriptionStart && user.subscriptionPlan !== \"none\") {\n",
    "      const startDate = new Date(user.subscriptionStart);\n",
    "      const currentDate = new Date();\n",
    "      if (user.subscriptionPlan === \"1month\") {\n",
    "        const endDate = new Date(startDate);\n",
    "        endDate.setMonth(endDate.getMonth() + 1);\n",
    "        hasActiveSubscription = currentDate >= startDate && currentDate < endDate;\n",
    "      } else if (user.subscriptionPlan === \"1year\") {\n",
    "        const endDate = new Date(startDate);\n",
    "        endDate.setFullYear(endDate.getFullYear() + 1);\n",
    "        hasActiveSubscription = currentDate >= startDate && currentDate < endDate;\n",
    "      }\n",
    "    }\n",
    "\n",
    "    res.status(200).json({ \n",
    "      user: {\n",
    "        username: user.username, \n",
    "        email: user.email,\n",
    "        subscriptionPlan: user.subscriptionPlan || 'none',\n",
    "        isSubscribed: user.isSubscribed || false,\n",
    "        subscriptionStart: user.subscriptionStart || null,\n",
    "        hasActiveSubscription\n",
    "      },\n",
    "      token \n",
    "    });\n",
    "\n",
    "  } catch (error) {\n",
    "    console.error(\"2FA Login verification error:\", error);\n",
    "    res.status(500).json({ message: \"Server error\", error: error.message });\n",
    "  }\n",
    "});\n",
    "\n",
    "// 2. Setup 2FA: Generate Secret & QR Code (Authenticated)\n",
    "app.post(\"/api/auth/2fa/setup\", authenticateToken, async (req, res) => {\n",
    "  try {\n",
    "    const user = await User.findById(req.user.userId);\n",
    "    if (!user) return res.status(404).json({ message: \"User not found\" });\n",
    "\n",
    "    // Generate secret\n",
    "    const secret = authenticator.generateSecret();\n",
    "    \n",
    "    // Save temporary secret to user (don't enable yet)\n",
    "    user.tempTwoFactorSecret = secret;\n",
    "    await user.save();\n",
    "\n",
    "    // Generate QR Code\n",
    "    const otpauth = authenticator.keyuri(user.email, \"StegaSphere\", secret);\n",
    "    const imageUrl = await QRCode.toDataURL(otpauth);\n",
    "\n",
    "    res.status(200).json({ secret, qrCode: imageUrl });\n",
    "\n",
    "  } catch (error) {\n",
    "    console.error(\"2FA Setup error:\", error);\n",
    "    res.status(500).json({ message: \"Server error\" });\n",
    "  }\n",
    "});\n",
    "\n",
    "// 3. Enable 2FA: Verify code and activate (Authenticated)\n",
    "app.post(\"/api/auth/2fa/enable\", authenticateToken, async (req, res) => {\n",
    "  try {\n",
    "    const { code } = req.body;\n",
    "    const user = await User.findById(req.user.userId);\n",
    "    \n",
    "    if (!user || !user.tempTwoFactorSecret) {\n",
    "      return res.status(400).json({ message: \"Please request 2FA setup first\" });\n",
    "    }\n",
    "\n",
    "    const isValid = authenticator.check(code, user.tempTwoFactorSecret);\n",
    "    if (!isValid) {\n",
    "      return res.status(400).json({ message: \"Invalid code\" });\n",
    "    }\n",
    "\n",
    "    // Activate\n",
    "    user.twoFactorSecret = user.tempTwoFactorSecret;\n",
    "    user.isTwoFactorEnabled = true;\n",
    "    user.tempTwoFactorSecret = undefined; // Clear temp\n",
    "    await user.save();\n",
    "\n",
    "    res.status(200).json({ message: \"2FA Enabled successfully\" });\n",
    "  } catch (error) {\n",
    "    console.error(\"2FA Enable error:\", error);\n",
    "    res.status(500).json({ message: \"Server error\" });\n",
    "  }\n",
    "});\n",
    "\n",
    "// 4. Disable 2FA (Authenticated)\n",
    "app.post(\"/api/auth/2fa/disable\", authenticateToken, async (req, res) => {\n",
    "  try {\n",
    "    const user = await User.findById(req.user.userId);\n",
    "    user.isTwoFactorEnabled = false;\n",
    "    user.twoFactorSecret = undefined;\n",
    "    await user.save();\n",
    "    res.status(200).json({ message: \"2FA Disabled\" });\n",
    "  } catch (error) {\n",
    "    res.status(500).json({ message: \"Server error\" });\n",
    "  }\n",
    "});\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
